# Generated by Django 5.1.2 on 2024-10-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
